# Generated by Django 5.1.5 on 2025-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=20)),
                ('contact_phone', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=20)),
                ('lead_creation_time', models.DateTimeField()),
                ('lead_allocation_time', models.DateTimeField(blank=True, null=True)),
                ('department_name', models.CharField(max_length=20)),
                ('source_name', models.CharField(max_length=20)),
                ('contact_tool', models.CharField(max_length=20)),
                ('consultation_content', models.TextField()),
                ('cow_name', models.CharField(max_length=20)),
                ('follow_status', models.CharField(max_length=50)),
                ('follow_new_record', models.TextField()),
                ('follow_new_time', models.DateTimeField()),
                ('leads_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
