# Generated by Django 5.1.5 on 2025-02-12 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lead",
            new_name="Leads",
        ),
    ]
