# Generated by Django 5.1.5 on 2025-02-19 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0001_initial"),
        ("channel", "0001_initial"),
        ("component", "0001_initial"),
        ("cow", "0010_alter_cow_password"),
        ("department", "0002_alter_department_department_name"),
        ("leads", "0001_initial"),
        ("proceeding", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leads",
            old_name="leads_number",
            new_name="lead_code",
        ),
        migrations.RemoveField(
            model_name="leads",
            name="contact_tool",
        ),
        migrations.RemoveField(
            model_name="leads",
            name="follow_status",
        ),
        migrations.RemoveField(
            model_name="leads",
            name="source_name",
        ),
        migrations.AddField(
            model_name="leads",
            name="channel_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="channel.channel",
                to_field="channel_code",
                verbose_name="来源",
            ),
        ),
        migrations.AddField(
            model_name="leads",
            name="component_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="component.component",
                to_field="component_code",
                verbose_name="联络工具",
            ),
        ),
        migrations.AddField(
            model_name="leads",
            name="proceeding_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proceeding.proceeding",
                to_field="proceeding_code",
                verbose_name="跟进状态",
            ),
        ),
        migrations.AlterField(
            model_name="leads",
            name="business_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="business.business",
                to_field="business_code",
                verbose_name="业务",
            ),
        ),
        migrations.AlterField(
            model_name="leads",
            name="contact_person",
            field=models.CharField(max_length=20, verbose_name="联系人"),
        ),
        migrations.AlterField(
            model_name="leads",
            name="contact_phone",
            field=models.CharField(max_length=20, verbose_name="联系电话"),
        ),
        migrations.AlterField(
            model_name="leads",
            name="cow_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cow.cow",
                to_field="username",
                verbose_name="线索负责人",
            ),
        ),
        migrations.AlterField(
            model_name="leads",
            name="department_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="department.department",
                to_field="department_code",
                verbose_name="部门",
            ),
        ),
        migrations.AlterField(
            model_name="leads",
            name="product_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.product",
                to_field="product_code",
                verbose_name="产品",
            ),
        ),
        migrations.CreateModel(
            name="LeadFollowUpRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follow_up_content", models.TextField(verbose_name="跟进内容")),
                (
                    "follow_up_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="跟进时间"),
                ),
                (
                    "follow_up_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cow.cow",
                        to_field="username",
                        verbose_name="跟进人",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up_records",
                        to="leads.leads",
                        verbose_name="关联线索",
                    ),
                ),
            ],
            options={
                "verbose_name": "线索跟进记录",
                "verbose_name_plural": "线索跟进记录",
                "ordering": ["-follow_up_time"],
            },
        ),
    ]
