# Generated by Django 5.1.5 on 2025-02-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_rename_leads_number_leads_lead_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leads",
            name="lead_status",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="线索状态"),
        ),
    ]
