# Generated by Django 5.1.5 on 2025-02-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_leads_lead_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leads",
            name="lead_creation_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
