# Generated by Django 5.1.5 on 2025-02-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_leads_lead_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='consultation_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='follow_new_record',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='follow_new_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_status',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='线索状态'),
        ),
    ]
