# Generated by Django 5.1.5 on 2025-02-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysetting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_name',
            new_name='contact_tool',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follow_name',
            new_name='follow_status',
        ),
    ]
