# Generated by Django 5.1.5 on 2025-02-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privileges_name', models.CharField(max_length=20)),
                ('privileges_code', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
