# Generated by Django 5.1.5 on 2025-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=40)),
                ('deal_date', models.DateField()),
                ('contact_person', models.CharField(max_length=20)),
                ('contact_phone', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=20)),
                ('cow_name', models.CharField(max_length=20)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=20)),
                ('source_name', models.CharField(max_length=20)),
                ('lead_creation_time', models.DateField()),
                ('order_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
