# Generated by Django 5.1.5 on 2025-02-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='business_type',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='department',
            new_name='cow_name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='lead_source',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='lead_creation_date',
            new_name='lead_creation_time',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='product_type',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='responsible_person',
            new_name='source_name',
        ),
    ]
