# Generated by Django 5.1.5 on 2025-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_name', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=30)),
                ('privileges_name', models.CharField(max_length=20)),
                ('receive_leads_total', models.IntegerField(default=0)),
                ('cow_code', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
