# Generated by Django 5.1.5 on 2025-02-17 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0001_initial'),
        ('department', '0002_alter_department_department_name'),
        ('privileges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_employee_name', models.CharField(max_length=20, verbose_name='员工姓名')),
                ('cow_leads_total', models.PositiveIntegerField(default=0, verbose_name='线索总量')),
                ('cow_follow_up_count', models.PositiveIntegerField(default=0, verbose_name='跟进数量')),
                ('cow_returned_to_public_count', models.PositiveIntegerField(default=0, verbose_name='回退公海数量')),
                ('cow_deal_count', models.PositiveIntegerField(default=0, verbose_name='成交数量')),
                ('cow_first_deal_total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='首单成交总额')),
                ('cow_total_deal_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='成交总额')),
                ('cow_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='所属部门')),
                ('cow_privileges', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='privileges.privileges', verbose_name='权限')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
        ),
        migrations.DeleteModel(
            name='Cow',
        ),
    ]
