# Generated by Django 5.1.5 on 2025-02-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Privileges',
            new_name='Cow',
        ),
    ]
