# Generated by Django 5.1.5 on 2025-02-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0002_employee_delete_cow'),
        ('department', '0002_alter_department_department_name'),
        ('privileges', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Cow',
        ),
    ]
