# Generated by Django 5.1.5 on 2025-02-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0003_rename_employee_cow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='cow_customer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='客户数量'),
        ),
    ]
