# Generated by Django 5.1.5 on 2025-02-18 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0006_alter_cow_cow_department_alter_cow_cow_privileges'),
        ('department', '0002_alter_department_department_name'),
        ('privileges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='cow_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', to_field='department_code', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='cow_privileges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='privileges.privileges', to_field='privileges_code', verbose_name='权限'),
        ),
    ]
