# Generated by Django 5.1.5 on 2025-02-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cow", "0007_alter_cow_cow_department_alter_cow_cow_privileges"),
    ]

    operations = [
        migrations.AddField(
            model_name="cow",
            name="password",
            field=models.CharField(default=111111, max_length=128, verbose_name="密码"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cow",
            name="username",
            field=models.CharField(
                default=1111111, max_length=30, unique=True, verbose_name="用户名"
            ),
            preserve_default=False,
        ),
    ]
