# Generated by Django 5.1.5 on 2025-02-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cow", "0008_cow_password_cow_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cow",
            name="password",
            field=models.CharField(default="123456", max_length=128, verbose_name="密码"),
        ),
    ]
