# Generated by Django 5.1.5 on 2025-02-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cow", "0009_alter_cow_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cow",
            name="password",
            field=models.CharField(max_length=128, verbose_name="密码"),
        ),
    ]
