# Generated by Django 5.1.5 on 2025-02-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cow", "0010_alter_cow_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="cow",
            name="cow_email",
            field=models.EmailField(
                blank=True, max_length=50, null=True, verbose_name="邮箱"
            ),
        ),
    ]
